export const CART_ACTION_TYPES = {
    SET_IS_OPEN_CART: "cart/SET_IS_OPEN_CART",
    ADD_ITEM_TO_CART: "cart/ADD_ITEM_TO_CART",
    DECREASE_ITEM_QUANTITY: "cart/DECREASE_ITEM_QUANTITY",
    DELETE_ITEM: "cart/DELETE_ITEM",
};
